---
title: "Introduction to R Studio"
subtitle: "Entering the World of Quantitive Research with R"
author: "Lenard Dome"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
  xaringan::moon_reader:
    css: ["libs/default.css", "libs/default-fonts.css"]
    seal: true 
    self_contained: true
    nature:
      ratio: "21:11"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(emo)
library(fontawesome)
```

class: middle center inverse

**13.30** Quick Introduction (30 min)

**14.00** Follow on worksheets (approx. 45 minutes)

**14.45** Take a break and recharge (15 mins)

**15.00** Continue with worksheets (approx. 1 hour and 30 minutes)

---

class: top left inverse

# Quantitative Research

> One of the many goals of quantitative methods is to make reliable conclusions from the observations you make. 

<br><br>

* Hypothesis: Given condition X, we will see people do Y. 
* Measurement: Make observations under condition X.
* **Test: Did we observe people do Y? (Today's focus)**

.footnote[

.bold[*] Andy Wills: Science, Truth, Honesty [slides](https://www.andywills.info/critical-thinking/ScienceTruthHonestyInteract.pdf) [notes](https://www.andywills.info/critical-thinking/ScienceTruthHonestyNotesInteract.html) [course](https://www.andywills.info/critical-thinking/#ct-lectures)

.bold[*] Todd Gureckis: Why do we learn statistics? [video](https://vimeo.com/508505679) [chapter](http://gureckislab.org/courses/spring21/labincp/chapters/01/00-whystats.html#video-lecture)

]

---

class: middle left inverse

# Why statistics?

While human reasoning is powerful, it is influenced by human biases, limited cognitive capacity, and also by simple tiredness.
It is actually hard to evaluate evidence without pre-existing beliefs.

---

class: middle left inverse

# Replicability

One of the most important endeavours that science as a social enterprise can engage is to verify each other's observations through independent replications.
The reason behind this is simple: repeated observations will increase our confidence that the effect is real.


---

class: middle left inverse

# Quantitative Backlash

---

class: top left inverse

# Quantitative Backlash

[Open Science Collaboration (2015)](https://doi.org/10.1126/science.aac4716)

|                                                                     | *p* < 0.05 |
| ------------------------------------------------------------------- | ---------: |
| Journal of Personality and Social Psychology                        |        23% |
| Journal of Experimental Psychology: Learning, Memory, and Cognition |        48% |
| Psychological Science (social)                                      |        29% |
| Psychological Science (cognitiive)                                  |        53% |
| Overall                                                             |        36% |


.footnote[

.bold[*] Andy Wills: Fix the replication Crisis [video](https://www.youtube.com/watch?v=_OqiTVq12Pk)

.bold[*] David Shanks: The replication crisis in psychology [video](https://www.youtube.com/watch?v=Zz627CecmgU)

.bold[*] David Shanks: Does social science tell the truth? [video](https://www.youtube.com/watch?v=Jt7gEAoUl8s)

.bold[*] Priya Silverstein: Easing into open science [video](https://www.youtube.com/watch?v=owJaD3UiseQ)

]


---

class: middle left inverse

# Some causes we can fix by changing how we do and document our analysis


There are many, but we will only focus on a subset of things...

---

class: middle left inverse

1. Misunderstanding of statistics
> The major component of our new approach is to open up our analysis and analysis methods to others. This requires us understanding what we are doing.

---

class: middle left inverse

1. Misunderstanding of statistics
> The major component of our new approach is to open up our analysis and analysis methods to others. This requires us understanding what we are doing.
2. Low reproducibility (specifically our **analysis**)
> Openly sharing every bit of details allows researchers to inspect what we have done and discover errors or learn something new about our work.

---

class: middle left inverse

1. Misunderstanding of statistics
> The major component of our new approach is to open up our analysis and analysis methods to others. This requires us understanding what we are doing.
2. Low reproducibility (specifically our **analysis**)
> Openly sharing every bit of details allows researchers to inspect what we have done and discover errors or learn something new about our work.
3. Poor records
> Archiving is one of the most important part of research. We need to record what we have done so people can build on transparent foundations.

---

class: middle left inverse

1. Misunderstanding of statistics
> The major component of our new approach is to open up our analysis and analysis methods to others. This requires us understanding what we are doing.
2. Low reproducibility (specifically our **analysis**)
> Openly sharing every bit of details allows researchers to inspect what we have done and discover errors or learn something new about our work.
3. Poor records
> Archiving is one of the most important part of research. We need to record what we have done so people can build on transparent foundations.
4. Not sharing data openly
> Sharing data is the hallmark of research. Also remember that majority of research is funded by regular tax-paying people.

---

class: middle left inverse

# But why do we exactly use R?

.footnote[

.bold[*] Danielle Navarro: R for Psychological Science? [video](https://www.youtube.com/watch?v=xFkEbYk0C0Q)

.bold[*] [Some reasons to use R](https://www.andywills.info/rminr/why-r-student.html)

]

---

class: middle left inverse

* Free as in Freedom

> Costs £0.


---

class: middle left inverse

* R is Free as in Freedom

> Costs £0.

* R documents your analysis

> Any conclusion people make from data should stand independent of the person making
> the conclusion.

---

class: middle left inverse

* R is Free as in Freedom

> Costs £0.

* R documents your analysis

> Any conclusion people make from data should stand independent of the person making
> the conclusion.

* R is Open Source

> If you do the same tests on the same data, but get a different result, the
> difference must be about how the test was programmed.


---

class: middle left inverse

* R is Free as in Freedom

> Costs £0.

* R Documents Your Analysis

> Any conclusion people make from data should stand independent of the person making
> the conclusion.

* R is Open Source

> If you do the same tests on the same data, but get a different result, the
> difference must be about how the test was programmed.

* R is Good at Data preprocessing

> 80% of time is spent on data preprocessing, see
> [article](https://www.forbes.com/sites/gilpress/2016/03/23/data-preparation-most-time-consuming-least-enjoyable-data-science-task-survey-says/#5e7ed02f6f63).
> R is superb at preprocessing, saving a large amount of time - especially for
> multiple projects.


---

class: middle left inverse

# The Analysis Pipeline

Today, we will go through a very rough and elementary model of analysis:

* Start from importing the raw data for analysis
* Continue by exploring the data
* Keep on going by studying properties of the data
* End by having a single reliable conclusion about your data

---

class: middle left inverse

# The Analysis Pipeline

Today, we will go through a very rough and elementary model of analysis:

* Start from importing the raw data for analysis
* Continue by exploring the data
* Keep on going by studying properties of the data
* End by having a single reliable conclusion about your data

**The published paper is only a summary of what you have done, it is not the perfect
record of how you arrived at a certain statistical conclusion.**

---

class: middle left inverse

# The Open Analysis Pipeline

Using R allows you to complement your paper. It will let you:

* record every analysis step.
* inspect the way the results are calculated.
* reproduce analysis and let others reproduce yours.

---

class: top left inverse

# What is going to happen today?

<br><br>

**Complete a worksheets!!**

Here are the worksheets in the order you should go through them.
They are part of [RMINR](https://www.andywills.info/rminr/#vbgtr), that has been developed at the University of Plymouth as an in-house teaching material.

* [Using RStudio](https://www.andywills.info/rminr/using_rstudio.html): Brief introduction to the software
* [Exploring data](https://www.andywills.info/rminr/vbg_explore.html): Loading data, calculating means
* [Group differences](https://www.andywills.info/rminr/vbg_groups.html): Grouping, density plots, filtering.
* [Evidence, part 1](https://www.andywills.info/rminr/vbg_evidence.html): Bayesian and traditional t-tests
* [Evidence, part 2](https://www.andywills.info/rminr/vbg_corr.html): Bayes and traditional correlation, scatterplot

---

class: top left inverse

# I finished... what now?

If you completed the Very Brief Guide to R worksheets, there is a few things you should look at:

* [Data Management](https://www.andywills.info/rminr/data-github.html): some good introduction on good and open practices about how you should be dealing with data.
* [Data preprocessing](https://www.andywills.info/rminr/preproc.html): De-duplicating data, excluding participants, log transform.
* [Statistical Power](https://www.andywills.info/rminr/power.html): power is a very important concept, that is concerned with getting enough evidence to support your conclusions.
* [Children's language development](https://www.andywills.info/rminr/cs-picture-naming-wide.html): preprocessing, Bayesian t-test, tables of descriptive statistics, correlations, half-violin plot, Wilcoxon test. 

---

class: top left inverse

# Contacts

If you have any questions about R, statistics, research in general, do not hesitate to contact me:

`r emo::ji("man")` lenard.dome@plymouth.ac.uk


* `r emo::ji("chart")` Slides are availabe at [lenarddome.github.io/teaching](https://lenarddome.github.io/teaching/)
* `r emo::ji("notebook")` All other material, including notes, can be found on [GitHub `r fontawesome::fa("github")`](https://github.com/lenarddome/CPSY622-introduction-to-data-analysis)

<!-- style -->

<style>

body {
  background: #2e3440;
}

h1.title {
  color: #a3be8c;
}

h1.subtitle {
  font-size: 42px;
}

.container{
    display: flex;
}

.col{
    flex: 1;
}

div.sourceCode {
  background-color: #2e3440;
}

.sourceCode {
  background-color: #393f4b;
}

.reveal section img {
  border: 30px solid #e0e1e2;
  border-radius: 10px;
  display: block;
  margin-left: auto;
  margin-right: auto;
  }

.reveal p {
  text-align: left;
}

.reveal ul {
  display: block;
}

.reveal ol {
  display: block;
}

</style>
